name: random_string_generator
description: An easy to use, customizable and secure random string generator. Can also be used as a password generator.
homepage: https://github.com/adrianflutur/random_string_generator
version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
